$(document).ready(function(){
	$('.info_home').hide();
	$('a[href^="#home"]').click(function(){
		$('.info_home').fadeToggle();
	});
	$('.info_dev').hide();
	$('a[href^="#developer"]').click(function(){
		$('.info_dev').fadeToggle();
	});
	$('.info_des').hide();
	$('a[href^="#design"]').click(function(){
		$('.info_des').fadeToggle();
	});
	$('.info_seo').hide();
	$('a[href^="#seo"]').click(function(){
		$('.info_seo').fadeToggle();
	});
	$('.info_regform').hide();
	$('a[href^="#regform"]').click(function(){
		$('.info_regform').fadeToggle();
	});
	$('.info_portfolio').hide();
	$('a[href^="#portfolio"]').click(function(){
		$('.info_portfolio').fadeToggle();
	});
	$('.info_services').hide();
	$('a[href^="#services"]').click(function(){
		$('.info_services').fadeToggle();
	});
	$('.info_contacts').hide();
	$('a[href^="#contacts"]').click(function(){
		$('.info_contacts').slideToggle();
	});
});//end ready