$(document).ready(function(){
    $('.slider_2').hide();
    $('.slider_3').hide();
    $('.slider_1').show(function(){
        $('.sub1').addClass('.slider_active');
    });
    $('.sub2').click(function(){
        $('.slider_1').hide();
        $('.slider_3').hide();
        $('.slider_2').fadeIn(10);
        $('.sub2').addClass('.slider_active');
    });
    $('.sub3').click(function(){
        $('.slider_1').hide();
        $('.slider_2').hide()
        $('.slider_3').fadeIn(10);
        $('.sub3').addClass('.slider_active');
    });
    $('.sub1').click(function(){
        $('.slider_3').hide();
        $('.slider_2').hide()
        $('.slider_1').fadeIn(10);
        $('.sub1').addClass('.slider_active');
    });
});